import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import { LearningProgressProvider } from "@/contexts/LearningProgressContext";
import { ReviewDeckProvider } from "@/contexts/ReviewDeckProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "UPCAT Filipino Adaptive Reviewer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} bg-gray-200`}>
        <LearningProgressProvider>
          <ReviewDeckProvider>{children}</ReviewDeckProvider>
        </LearningProgressProvider>
      </body>
    </html>
  );
}
