# Generated by Django 5.2.9 on 2025-12-27 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('vocabulary', 'Vocabulary'), ('grammar', 'Grammar'), ('sentence-construction', 'Sentence Construction'), ('reading-comprehension', 'Reading Comprehension')], max_length=50)),
                ('completion_percentage', models.IntegerField(default=0)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('mastery_level', models.CharField(choices=[('beginner', 'Beginner'), ('developing', 'Developing'), ('proficient', 'Proficient'), ('advanced', 'Advanced'), ('master', 'Master')], default='beginner', max_length=20)),
                ('current_difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'module_progress',
            },
        ),
        migrations.CreateModel(
            name='ExerciseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(choices=[('flashcards', 'Flashcards'), ('quiz', 'Quiz'), ('fill-blanks', 'Fill in the Blanks')], max_length=20)),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('available', 'Available'), ('in-progress', 'In Progress'), ('completed', 'Completed')], default='locked', max_length=20)),
                ('attempts', models.IntegerField(default=0)),
                ('best_score', models.IntegerField(blank=True, null=True)),
                ('last_score', models.IntegerField(blank=True, null=True)),
                ('last_difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10)),
                ('first_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='progress.moduleprogress')),
            ],
            options={
                'db_table': 'exercise_progress',
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(max_length=10)),
                ('score', models.IntegerField()),
                ('missed_low_freq', models.IntegerField(default=0)),
                ('similar_choice_errors', models.IntegerField(default=0)),
                ('error_tags', models.JSONField(default=list)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('exercise_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_history', to='progress.exerciseprogress')),
            ],
            options={
                'db_table': 'performance_metrics',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ReviewDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_id', models.IntegerField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('last_reviewed', models.DateTimeField(blank=True, null=True)),
                ('times_reviewed', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_deck', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'review_deck',
            },
        ),
        migrations.CreateModel(
            name='SRSCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_id', models.IntegerField()),
                ('repetitions', models.IntegerField(default=0)),
                ('easiness_factor', models.FloatField(default=2.5)),
                ('interval', models.IntegerField(default=0)),
                ('next_review', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_reviewed', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='srs_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'srs_cards',
            },
        ),
        migrations.AddIndex(
            model_name='moduleprogress',
            index=models.Index(fields=['user', 'module'], name='module_prog_user_id_432e46_idx'),
        ),
        migrations.AddIndex(
            model_name='moduleprogress',
            index=models.Index(fields=['updated_at'], name='module_prog_updated_78593b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='moduleprogress',
            unique_together={('user', 'module')},
        ),
        migrations.AddIndex(
            model_name='exerciseprogress',
            index=models.Index(fields=['module_progress', 'exercise_type'], name='exercise_pr_module__d58596_idx'),
        ),
        migrations.AddIndex(
            model_name='exerciseprogress',
            index=models.Index(fields=['status'], name='exercise_pr_status_be09a4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='exerciseprogress',
            unique_together={('module_progress', 'exercise_type')},
        ),
        migrations.AddIndex(
            model_name='performancemetrics',
            index=models.Index(fields=['exercise_progress', 'timestamp'], name='performance_exercis_0975b8_idx'),
        ),
        migrations.AddIndex(
            model_name='performancemetrics',
            index=models.Index(fields=['difficulty'], name='performance_difficu_dfff34_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewdeck',
            index=models.Index(fields=['user', 'added_at'], name='review_deck_user_id_ff6fa6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewdeck',
            unique_together={('user', 'word_id')},
        ),
        migrations.AddIndex(
            model_name='srscard',
            index=models.Index(fields=['user', 'next_review'], name='srs_cards_user_id_5db3bd_idx'),
        ),
        migrations.AddIndex(
            model_name='srscard',
            index=models.Index(fields=['word_id'], name='srs_cards_word_id_0356cd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='srscard',
            unique_together={('user', 'word_id')},
        ),
    ]
